/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signos.inicio;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jareth Manrique
 */
public class Inicio extends javax.swing.JFrame {

    DefaultComboBoxModel modelo = new DefaultComboBoxModel();
    DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();
    DefaultComboBoxModel modelo3 = new DefaultComboBoxModel();
    int dia[] = new int[32];
    String meses[] = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio",
        "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    int año[] = new int[2021];

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setTitle("Signos Zodiacales");
        datosModelo();
    }

    private void datosModelo() {
        modelo.addElement("Día");
        modelo2.addElement("Mes");
        modelo3.addElement("Año");
        for (int i = 1; i < dia.length; i++) {
            modelo.addElement(String.valueOf(i));
        }
        for (String mese : meses) {
            modelo2.addElement(String.valueOf(mese));
        }
        for (int i = 1950; i < año.length; i++) {
            modelo3.addElement(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Signos Zodiacales");

        jComboBox1.setModel(this.modelo);

        jComboBox2.setModel(this.modelo2);

        jComboBox3.setModel(this.modelo3);

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Ingresa tu fecha de nacimiento");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(109, 109, 109))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dato1 = (String) jComboBox1.getSelectedItem();
        String dato2 = (String) jComboBox2.getSelectedItem();
        String dato3 = (String) jComboBox3.getSelectedItem();
        Image imgac = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/acuario.png"));
        Image imgar = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/aries.png"));
        Image imgcan = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/cancer.png"));
        Image imgcap = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/capricornio.png"));
        Image imges = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/escorpio.png"));
        Image imgge = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/geminis.png"));
        Image imgle = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/leo.png"));
        Image imgli = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/libra.png"));
        Image imgpi = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/piscis.png"));
        Image imgsa = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/sagitario.png"));
        Image imgta = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/tauro.png"));
        Image imgvi = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/signos/recursos/virgo.png"));

        //REVISAR QUE LA FECHA SEA CORRECTA
        if (dato1 == "Día" || dato2 == "Mes" || dato3 == "Año") {
            JOptionPane.showMessageDialog(rootPane, "SELECCIONA DÍA, MES Y AÑO", "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (dato1.equals("30") || dato1.equals("29") && dato2.equals("Febrero")) {
            JOptionPane.showMessageDialog(rootPane, "FECHA INCORRECTA", "Informacion",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (dato1.equals("31")) {
            if (dato2.equals("Febrero") || dato2.equals("Abril") || dato2.equals("Junio")
                    || dato2.equals("Septiembre") || dato2.equals("Noviembre")) {
                JOptionPane.showMessageDialog(rootPane, "FECHA INCORRECTA", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
        //PEDIR NOMBRE
        /*String clave = JOptionPane.showInputDialog(rootPane, "Escriba su nombre", "Nombre",
                JOptionPane.QUESTION_MESSAGE);
        if (clave == null || clave.isEmpty() || clave.regionMatches(0, " ", 0, 1)) {
            JOptionPane.showMessageDialog(rootPane, "Escribe algo",
                    "Titulo", JOptionPane.INFORMATION_MESSAGE);
        }*/
        //Calculos
        if (dato2 == "Enero") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Capricornio", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgcap.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("20") || dato1.equals("21") || dato1.equals("22")
                    || dato1.equals("23") || dato1.equals("24") || dato1.equals("25") || dato1.equals("26")
                    || dato1.equals("27") || dato1.equals("28") || dato1.equals("29") || dato1.equals("30")
                    || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Acuario", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgac.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Febrero") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Acuario", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgac.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("19") || dato1.equals("20") || dato1.equals("21")
                    || dato1.equals("22") || dato1.equals("23") || dato1.equals("24") || dato1.equals("25")
                    || dato1.equals("26") || dato1.equals("27") || dato1.equals("28")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Piscis", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgpi.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Marzo") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Piscis", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgpi.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("21") || dato1.equals("22") || dato1.equals("23")
                    || dato1.equals("24") || dato1.equals("25") || dato1.equals("26") || dato1.equals("27")
                    || dato1.equals("28") || dato1.equals("29") || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Aries", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgar.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Abril") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Aries", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgar.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("20") || dato1.equals("21") || dato1.equals("22")
                    || dato1.equals("23") || dato1.equals("24") || dato1.equals("25") || dato1.equals("26")
                    || dato1.equals("27") || dato1.equals("28") || dato1.equals("29") || dato1.equals("30")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Tauro", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgta.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Mayo") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Tauro", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgta.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("21") || dato1.equals("22") || dato1.equals("23")
                    || dato1.equals("24") || dato1.equals("25") || dato1.equals("26") || dato1.equals("27")
                    || dato1.equals("28") || dato1.equals("29") || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Géminis", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgge.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Junio") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Géminis", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgge.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("21") || dato1.equals("22") || dato1.equals("23")
                    || dato1.equals("24") || dato1.equals("25") || dato1.equals("26") || dato1.equals("27")
                    || dato1.equals("28") || dato1.equals("29") || dato1.equals("30")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Cáncer", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgcan.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Julio") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21") || dato1.equals("22")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Cáncer", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgcan.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("23") || dato1.equals("24") || dato1.equals("25")
                    || dato1.equals("26") || dato1.equals("27") || dato1.equals("28") || dato1.equals("29")
                    || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Leo", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgle.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Agosto") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21") || dato1.equals("22")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Leo", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgle.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("23") || dato1.equals("24") || dato1.equals("25")
                    || dato1.equals("26") || dato1.equals("27") || dato1.equals("28") || dato1.equals("29")
                    || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Virgo", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgvi.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Septiembre") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21") || dato1.equals("22")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Virgo", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgvi.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("23") || dato1.equals("24") || dato1.equals("25")
                    || dato1.equals("26") || dato1.equals("27") || dato1.equals("28") || dato1.equals("29")
                    || dato1.equals("30")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Libra", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgli.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Octubre") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21") || dato1.equals("22")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Libra", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgli.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("23") || dato1.equals("24") || dato1.equals("25")
                    || dato1.equals("26") || dato1.equals("27") || dato1.equals("28") || dato1.equals("29")
                    || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Escorpio", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imges.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Noviembre") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Escorpio", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imges.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("22") || dato1.equals("23") || dato1.equals("24")
                    || dato1.equals("25") || dato1.equals("26") || dato1.equals("27") || dato1.equals("28")
                    || dato1.equals("29") || dato1.equals("30")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Sagitario", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgsa.getScaledInstance(50, 50, 50)));
            }
        }
        if (dato2 == "Diciembre") {
            if (dato1.equals("1") || dato1.equals("2") || dato1.equals("3")
                    || dato1.equals("4") || dato1.equals("5") || dato1.equals("6") || dato1.equals("7")
                    || dato1.equals("8") || dato1.equals("9") || dato1.equals("10") || dato1.equals("11")
                    || dato1.equals("12") || dato1.equals("13") || dato1.equals("14") || dato1.equals("15")
                    || dato1.equals("16") || dato1.equals("17") || dato1.equals("18") || dato1.equals("19")
                    || dato1.equals("20") || dato1.equals("21")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Sagitario", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgsa.getScaledInstance(50, 50, 50)));
            } else if (dato1.equals("22") || dato1.equals("23")
                    || dato1.equals("24") || dato1.equals("25") || dato1.equals("26") || dato1.equals("27")
                    || dato1.equals("28") || dato1.equals("29") || dato1.equals("30") || dato1.equals("31")) {
                JOptionPane.showMessageDialog(rootPane, "Tu signo es: Capricornio", "Informacion",
                        JOptionPane.INFORMATION_MESSAGE,new ImageIcon(imgcap.getScaledInstance(50, 50, 50)));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
